lib/chat_app_web/router.ex
defmodule ChatAppWeb.Router do
  use ChatAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatAppWeb do
    pipe_through :browser


    get "/", PageController, :index
    post "/rooms", RoomController, :enter
    get "/:name/rooms", RoomController, :index
    get "/:name/rooms/new", RoomController, :new
    get "/:name/rooms/:id", RoomController, :show
    post "/:name/rooms", RoomController, :create
    delete "/:name/rooms/:id", RoomController, :delete
    post "/:name/rooms/:id/messages", MessageController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatAppWeb do
  #   pipe_through :api
  # end
end

lib/chat_app/application.ex
defmodule ChatApp.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      ChatApp.Repo,
      # Start the endpoint when the application starts
      ChatAppWeb.Endpoint
      # Starts a worker by calling: ChatApp.Worker.start_link(arg)
      # {ChatApp.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: ChatApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ChatAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/chat_app/message.ex
defmodule ChatApp.Message do
  use Ecto.Schema
  import Ecto.Changeset
  use Arc.Ecto.Schema

  schema "messages" do
    field :message, :string
    field :image, ChatApp.ImageUploader.Type
    # field :image, :string
    belongs_to :room, ChatApp.Room
    timestamps()
  end

  @doc false
  def changeset(message, attrs) do
    message
    |> cast(attrs, [:message])
    # |> validate_required([:message])
    |> cast_attachments(attrs, [:image])
  end

  def get_room_info(id) do
    ChatApp.Repo.get(ChatApp.Room, id) |> ChatApp.Repo.preload(:messages)
  end
end

lib/chat_app/repo.ex
defmodule ChatApp.Repo do
  use Ecto.Repo,
    otp_app: :chat_app,
    adapter: Ecto.Adapters.Postgres
end

lib/chat_app/room.ex
defmodule ChatApp.Room do
  use Ecto.Schema
  import Ecto.Changeset

  schema "rooms" do
    field :description, :string
    field :name, :string
    has_many :messages, ChatApp.Message
    timestamps()
  end

  @doc false
  def changeset(room, attrs) do
    room
    |> cast(attrs, [:name, :description])
    |> validate_required([:name, :description])
  end
end

lib/chat_app_web/controllers/message_controller.ex
defmodule ChatAppWeb.MessageController do
  use ChatAppWeb, :controller
  import Logger
  alias ChatApp.Message
  alias ChatApp.Repo
  def create(conn, %{"message" => message_params, "name" => name, "id" => room_id}) do
    changeset = Ecto.build_assoc(ChatApp.Room |> ChatApp.Repo.get(room_id), :messages)
    |> Message.changeset(%{image: message_params["image"], message: " "})
    case Repo.insert(changeset) do
      {:ok, message} ->
        conn
        |> redirect(to: Routes.room_path(conn, :show, name, room_id))
    end
  end
end

lib/chat_app_web/controllers/page_controller.ex
defmodule ChatAppWeb.PageController do
  use ChatAppWeb, :controller
  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/chat_app_web/controllers/room_controller.ex
defmodule ChatAppWeb.RoomController do
  use ChatAppWeb, :controller
  alias ChatApp.Room
  alias ChatApp.Repo
  alias ChatApp.Message
  def enter(conn, %{"username" => username}) do
    rooms = Room |> Repo.all
    render(conn, "index.html", rooms: rooms, username: username)
  end
  def index(conn, %{"name" => name}) do
    rooms = Room |> Repo.all
    render(conn, "index.html", rooms: rooms, username: name)
  end
  def show(conn, %{"id" => id, "name" => name}) do
    changeset = Message.changeset(%Message{}, %{})
    room = Room |> Repo.get(id)
    render(conn, "chatroom.html", room_id: id, name: name, changeset: changeset, room: room)
  end
  def new(conn, %{"name" => name}) do
    changeset = Room.changeset(%Room{}, %{})
    render(conn, "new.html", changeset: changeset, name: name)
  end
  def create(conn, %{"room" => room_params, "name" => name}) do
    changeset = Room.changeset(%Room{}, room_params)
    case Repo.insert(changeset) do
      {:ok, room} ->
        conn
        |> redirect(to: Routes.room_path(conn, :index, name))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, name: name)
    end
  end
  def delete(conn, %{"id" => id, "name" => name}) do
    room = Room |> Repo.get(id)
    Repo.delete(room)

    conn
    |> redirect(to: Routes.room_path(conn, :index, name))
  end
end

lib/chat_app_web/views/error_view.ex
defmodule ChatAppWeb.ErrorView do
  use ChatAppWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/chat_app_web/views/layout_view.ex
defmodule ChatAppWeb.LayoutView do
  use ChatAppWeb, :view
end

lib/chat_app_web/views/page_view.ex
defmodule ChatAppWeb.PageView do
  use ChatAppWeb, :view
end

lib/chat_app_web/views/room_view.ex
defmodule ChatAppWeb.RoomView do
  use ChatAppWeb, :view
end

lib/chat_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ChatApp · Phoenix Framework</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Economica:700" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-dark navbar-inverse bg-info text-white">
        <div class="logo link-text">
          <%= link("start|>ash", to: Routes.page_path(@conn, :index), class: "text-white") %>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/chat_app_web/templates/page/index.html.eex
<div class="top-page">
  <%= form_tag(Routes.room_path(@conn, :enter), method: :post)%>
    <div class="form-group">
      <input type="text" name="username" placeholder="名前を入力してください" required
        title="名前が入力されてないよ"></input>
      <button type="submit" class="btn btn-bg btn-success"> 始める </button>
  </form>
</div>

lib/chat_app_web/templates/room/chatroom.html.eex
<div class="sidebyside">
<div class="chatroom">
  <div id="messages"></div>
  <input id="username", type="hidden", value=<%= @name %>></input>
  <input id="room-id", type="hidden", value=<%= @room_id%>></input>
  <div class="input-form">
    <input id="chat-input" type="text" placeholder="入力してenterで送信！"></input>
    <%= form_for @changeset, Routes.message_path(@conn, :create, @name, @room_id), [multipart: true], fn f -> %>
      <%= file_input f, :image, required: true, id: "image-input", accept: "image/*" %>
      <%= error_tag f, :image %>
      <%= text_input f, :text, value: "", type: "hidden" %>
      <%= text_input f, :room_id, value: @room_id, type: "hidden" %>
      <%= submit "画像を送信", class: "btn btn-primary", id: "image-button", disabled: true %>
    <% end %>
  </div>
</div>
<div class="side-right-bar">
  <table class="table-default">
    <tr>
      <th>部屋名</th><td><%= @room.name %></td>
    </tr>
    <tr>
      <th>概要</th><td><%= @room.description %></td>
    </tr>
  </table>
  <%= link("ルーム一覧画面へ", to: Routes.room_path(@conn, :index, @name), class: "btn btn-info", id: "index-to-room") %>
</div>
</div>

lib/chat_app_web/templates/room/index.html.eex
<table class="table-hover">
  <thead class="thead-light">
    <tr>
      <th class="table-text">部屋の名前</th>
      <th class="table-text">部屋の説明</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for room <- @rooms do %>
    <div class="tb">
    <tr>
      <td class="table-text"><%= room.name %></td>
      <td class="table-text"><%= room.description%></td>
      <td><%= link("入室", to: Routes.room_path(@conn, :show, @username, room), method: :get, class: "btn btn-block btn-primary") %></td>
      <td><%= link("削除", to: Routes.room_path(@conn, :delete, @username, room), method: :delete, class: "btn btn-block btn-danger",
        data: [confirm: "部屋名「#{room.name}」を削除してもいいですか？"]) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="new-room">
  <%= link("新規ルーム作成", to: Routes.room_path(@conn, :new, @username), method: :get, class: "btn btn-lg btn-success") %>
</div>

lib/chat_app_web/templates/room/new.html.eex
<%= form_for @changeset, Routes.room_path(@conn, :create, @name), fn f -> %>

<div class="form-group">
  <label>タイトル（ 15文字以内 ）</label>
  <%= text_input f, :name, class: "form-control", maxlength: "15" %>
  <%= error_tag f, :name%>
</div>

<div class="form-group">
  <label>本文 ( 35文字以内 )</label>
  <%= text_input f, :description, class: "form-control", maxlength: "35" %>
  <%= error_tag f, :description %>
</div>

<%= submit "ルームを作成", class: "btn btn-primary" %>

<% end %>